"""`.longhaul/` → one self-contained HTML file.

No server, no build step, no network. The CSS is inlined, so the page opens from
a file:// URL, from a CI artifact, or on a machine that never ran the agent — and
it is equally a live monitor and a post-mortem.

`report` is in v0.1 rather than with the rest of the UI because it is the
debugging surface for the orchestrator: reading `state.json` by hand stops
working around day three.
"""

from __future__ import annotations

import html
import json
from pathlib import Path

from ..schema.plan import Plan
from ..schema.state import DONE, FAILED, HALTED, IN_PROGRESS, PARKED, SKIPPED, State
from .redact import redact

ASSETS = Path(__file__).parent / "assets"

STATUS_LABEL = {
    DONE: "done", FAILED: "failed", PARKED: "parked",
    HALTED: "halted", "in_progress": "running", "pending": "pending",
}


def _esc(text: object) -> str:
    return html.escape(str(text), quote=True)


def _counts(plan: Plan, state: State) -> dict[str, int]:
    counts = state.counts()
    counts["pending"] += sum(1 for t in plan.tasks if t.id not in state.tasks)
    return counts


def _rows(plan: Plan, state: State) -> str:
    out = []
    for task in sorted(plan.tasks, key=lambda t: (t.day, t.id)):
        ts = state.tasks.get(task.id)
        status = ts.status if ts else "pending"
        label = STATUS_LABEL.get(status, status)
        criteria = "".join(f"<li>{_esc(c)}</li>" for c in task.acceptance_criteria)

        extra = ""
        if ts and ts.pr_url:
            extra += (
                f'<div class="why"><a href="{_esc(ts.pr_url)}">PR #{_esc(ts.pr_number)}</a></div>'
            )
        # PARKED belongs here as much as FAILED: a parked task is one waiting on
        # a human, so hiding its reason hides the only thing they need to read.
        if ts and ts.status in (FAILED, HALTED, PARKED) and ts.last_error:
            # Agent output reaches the page verbatim, and report.html gets
            # committed, attached to issues and screenshotted.
            first = redact(ts.last_error).splitlines()[0]
            extra += f'<div class="why">{_esc(first[:200])}</div>'
        attempts = (
            f" · attempt {ts.attempts}" if ts and ts.attempts > 1 else ""
        )
        cost = f" · ${ts.cost_usd:.2f}" if ts and ts.cost_usd else ""

        out.append(
            f'<tr class="{_esc(status)}">'
            f'<td class="day">day {task.day}</td>'
            f"<td><span class='dot'></span>{_esc(label)}</td>"
            f"<td><strong>{_esc(task.title)}</strong>"
            f"<span class='day'>{_esc(attempts)}{_esc(cost)}</span>"
            f'<ul class="crit">{criteria}</ul>{extra}</td>'
            "</tr>"
        )
    return "\n".join(out)


def render_main(plan: Plan, state: State, ledger: list[dict] | None = None) -> str:
    """The <main> content, so the live server can swap it without a reload."""
    counts = _counts(plan, state)
    ledger = ledger or []

    tiles = [
        ("done", counts[DONE]), ("failed", counts[FAILED]),
        ("parked", counts[PARKED]), ("halted", counts[HALTED]),
        ("running", counts[IN_PROGRESS]),
        ("to go", counts["pending"]),
        ("agent calls", len(ledger)),
        ("spent", f"${state.total_cost_usd:.2f}"),
    ]
    tile_html = "".join(
        f'<div class="count"><b>{_esc(v)}</b><span>{_esc(k)}</span></div>' for k, v in tiles
    )

    risks = "".join(f"<li>{_esc(r)}</li>" for r in plan.risk_flags)
    risk_block = f"<h2>Risk flags</h2><ul class='crit'>{risks}</ul>" if risks else ""

    return f"""<main>
  <h1>{_esc(plan.project)}</h1>
  <p class="sub">{_esc(counts[DONE])} of {_esc(len(plan.tasks))} tasks ·
     {_esc(plan.target_days)} days · <code>{_esc(plan.profile)}</code></p>
  <div class="counts">{tile_html}</div>
  <h2>Plan</h2>
  <div class="wrap"><table>
    <thead><tr><th>Day</th><th>Status</th><th>Task and acceptance criteria</th></tr></thead>
    <tbody>{_rows(plan, state)}</tbody>
  </table></div>
  {risk_block}
  <footer>
    Generated by <a href="https://github.com/cybiqon-ai/longhaul">Longhaul</a>
    from <code>.longhaul/</code>. No network, no tracking — this file is the
    whole page. Last updated {_esc(state.updated_at)}.
  </footer>
</main>
"""


def render(
    plan: Plan, state: State, ledger: list[dict] | None = None, live: bool = False
) -> str:
    """The whole page. `live` adds the reconnecting update listener."""
    css = (ASSETS / "report.css").read_text(encoding="utf-8")
    script = f"<script>{(ASSETS / 'live.js').read_text(encoding='utf-8')}</script>" if live else ""
    return (
        "<!doctype html>\n"
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        f"<title>{_esc(plan.project)} — Longhaul</title>\n"
        f"<style>{css}</style>\n"
        f"{render_main(plan, state, ledger)}"
        f"{script}"
    )


def write(plan: Plan, state: State, out: Path, ledger: list[dict] | None = None) -> Path:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(plan, state, ledger), encoding="utf-8")
    return out


def summary(plan: Plan, state: State) -> dict:
    """The same numbers as the page, for callers that want data not markup."""
    counts = _counts(plan, state)
    # Every status, so the numbers reconcile against `tasks`. A summary whose
    # parts do not add up to the whole is the failure this project is named for:
    # an in-progress task was silently missing from an earlier version of this.
    buckets = (DONE, FAILED, PARKED, HALTED, IN_PROGRESS, SKIPPED, "pending")
    return {
        "project": plan.project,
        "target_days": plan.target_days,
        "tasks": len(plan.tasks),
        **{k: counts[k] for k in buckets},
        "total_cost_usd": state.total_cost_usd,
    }


def to_json(plan: Plan, state: State) -> str:
    return json.dumps(summary(plan, state), indent=2)
